name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-ci.yaml@0e28b7460f19fe58c15eb5e2855d5b6b675c7620 # main
    with:
      uv-extras: "dev tools import"
