name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-ci.yaml@5eea546e39c84d94bf3322bd1437f275738e9f2e # main
    with:
      uv-extras: "dev tools import"
