name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (e.g. v0.1.0)"
        required: true

jobs:
  image:
    permissions:
      contents: read
      packages: write
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-release.yaml@0ebf66c2f1d49dab51813d5d53788c742c3d16d9 # main
    with:
      tag: ${{ github.event.inputs.tag || '' }}
