name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build (e.g. v0.1.0)"
        required: true

jobs:
  image:
    permissions:
      contents: read
      packages: write
    uses: alexander-zimmermann/lares/.github/workflows/sidecar-python-release.yaml@9784bf7cf90dfe9109b7f431cb70bc838113f66d # main
    with:
      tag: ${{ github.event.inputs.tag || '' }}
